package http_test_pkg1;

public class Create_JSON {
	
	static String StringURL_MerchInq = "https://www.fdmerchantservices.com/MerchantOnBoarding/inquiryService";
	static String StringURL_MerchBoarding = "https://www.fdmerchantservices.com/MerchantOnBoarding/EasyPayBoarding";
	
	static String StringTestURN = "{ "
			+ "\"urn\" " + ":" + "\"IMS99911\" "
					+ "}";
	
	static String StringTestBoard = "{ "
			+ "\"urn\" " + ":" + "\"IMS99911\" "
					+ "}";

	static String StringTestBoardingAPI = 
			"{"
			+" \"sale_rep_name\" "+ ":" + " \"mukherri-7338954682\" ,"
			+" \"application_number\" "+ ":" + " \"999911\" ," 
			+" \"account_number\" "+ ":" + " \"00010999911\", "
			+" \"imob_ic_id\" "+ ":" + " \"7338954682\", "
			+" \"icid\" "+ ":" + " \"7338954682\", "
			+" \"merchant_grade\" "+ ":" + " \"PP\", "
			+" \"mobile_no_application_notification\" "+ ":" + " \"7338954682\", "
			+" \"mcc\" "+ ":" + " \"5944\", "
			+" \"standard_state\" "+ ":" + " \"West Bengal\", "
			+" \"standard_city\" "+ ":" + " \"SILIGURI\", "
			+" \"dispute_state\" "+ ":" + " \"West Bengal\", "
			+" \"dispute_city\" "+ ":" + " \"SILIGURI\", "
			+" \"principal1_state\" "+ ":" + " \"West Bengal\", "
			+" \"principal1_city\" "+ ":" + " \"SILIGURI\", "
			+" \"principal2_state\" "+ ":" + " \"West Bengal\", "
			+" \"principal2_city\" "+ ":" + " \"SILIGURI\", "
			+" \"principal1_position\" "+ ":" + " \"Authorised Signatory\", "
			+" \"account_date\" "+ ":" + " \"1984-02-13\", "
			+" \"total_annual_turnover\" "+ ":" + " \"99999999\", "
			+" \"total_annual_credit_turnover\" "+ ":" + " \"99999999\", "
			+" \"average_ticket_amount\" "+ ":" + " \"199999\", "
			+" \"merchant_type\" "+ ":" + " \"POS\", "
			+" \"channel\" "+ ":" + " \"ICICI EAZYPAY POS\", "
			+" \"connectivity_type\" "+ ":" + " \"ECOM\", "
			+" \"terminal_mode\" "+ ":" + " \"ECOM\", "
			+" \"template_id\" "+ ":" + " \"ECOM\", "
			+" \"quantity\" "+ ":" + " \"1\", "
			+" \"curency_code\" "+ ":" + " \"INR\", "
			+" \"soc_code\" "+ ":" + " \"NA\", "
			+" \"waiver\" "+ ":" + " \"NA\", "
			+" \"setupfee\" "+ ":" + " \"NA\", "
			+" \"gprs_rental_amount\" "+ ":" + " \"NA\", "
			+" \"gprs_rental_amount_monthly_or_annual\" "+ ":" + " \"NA\", "
			+" \"installed_or_deinstalled\" "+ ":" + " \"Silver 4\", "
			+" \"carded_or_uncarded\" "+ ":" + " \"Carded\", "
			+" \"payment_advice_charge\" "+ ":" + " \"0\", "
			+" \"qr_address\" "+ ":" + " \"\", "
			+" \"qr_pin\" "+ ":" + " \"\", "
			+" \"agreementSignedDate\" "+ ":" + " \"2019-04-19 12:40:06\", "
			+" \"terminalModel\" "+ ":" + " \"\", "
			+" \"termSerialNumber\" "+ ":" + " \"\", "
			+" \"trading_business_name\" "+ ":" + " \"SILIGURI RC\", "
			+" \"legal_name\" "+ ":" + " \"SILIGURI RC CO\", "
			+" \"business_registration\" "+ ":" + " \"AADFP3397A\", "
			+" \"web_address\" "+ ":" + " \"\", "
			+" \"trading_date\" "+ ":" + " \"1984-02-13\", "
			+" \"type_of_business\" "+ ":" + " \"E2\", "
			+" \"standard_address1\" "+ ":" + " \"SILIGURI RC SUPPLY COMPANY\", "
			+" \"standard_address2\" "+ ":" + " \"SILIGURI RC ADDA\", "
			+" \"standard_address3\" "+ ":" + " \"SILIGURI\", " 
			+" \"standard_pin_code\" "+ ":" + " \"688001\", "
			+" \"standard_telephone\" "+ ":" + " \"7338954682\", "
			+" \"standard_email\" "+ ":" + " \"siliguri@rc.com\", "
			+" \"standard_contact_name\" "+ ":" + " \"muk herri\", "
			+" \"dispute_address1\" "+ ":" + " \"SILIGURI RC SUPPLY COMPANY\", "
			+" \"dispute_address2\" "+ ":" + " \"SILIGURI RC ADDA\", "
			+" \"dispute_address3\" "+ ":" + " \"SILIGURI\", "
			+" \"dispute_pin_code\" "+ ":" + " \"688001\", "
			+" \"dispute_telephone\" "+ ":" + " \"7338954682\", "
			+" \"dispute_email\" "+ ":" + " \"siliguri@rc.com\", "
			+" \"dispute_contact_name\" "+ ":" + " \"muk herri\", "
			+" \"principal1_title\" "+ ":" + " \"MR\", "
			+" \"principal1_firstname\" "+ ":" + " \"muk\", "
			+" \"principal1_middlename\" "+ ":" + " \"anon\", "
			+" \"principal1_lastname\" "+ ":" + " \"herri\", "
			+" \"principal1_dob\" "+ ":" + " \"1984-01-13\", "
			+" \"principal1_address1\" "+ ":" + " \"SILIGURI RC SUPPLY COMPANY\", "
			+" \"principal1_address2\" "+ ":" + " \"SILIGURI RC ADDA\", "
			+" \"principal1_address3\" "+ ":" + " \"SILIGURI\", "
			+" \"principal1_pin_code\" "+ ":" + " \"688001\", "
			+" \"principal1_telephone\" "+ ":" + " \"7338954682\", "
			+" \"principal1_mobile\" "+ ":" + " \"7338954682\", "
			+" \"principal1_id_type\" "+ ":" + " \"Pan\", "
			+" \"principal1_passport\" "+ ":" + " \"ABBPB3213C\", "
			+" \"principal2_title\" "+ ":" + " \"MRS\", "
			+" \"principal2_firstname\" "+ ":" + " \"SANTOSH\", "
			+" \"principal2_middlename\" "+ ":" + " \"\", "
			+" \"principal2_lastname\" "+ ":" + " \"BANSAL\", "
			+" \"principal2_position\" "+ ":" + " \"PARTNER\", "
			+" \"principal2_dob\" "+ ":" + " \"1944-12-03\", "
			+" \"principal2_address1\" "+ ":" + " \"SILIGURI RC SUPPLY COMPANY\", "
			+" \"principal2_address2\" "+ ":" + " \"SILIGURI RC ADDA\", "
			+" \"principal2_address3\" "+ ":" + " \"SILIGURI\", "
			+" \"principal2_pin_code\" "+ ":" + " \"688001\", "
			+" \"principal2_telephone\" "+ ":" + " \"7338954682\", "
			+" \"principal2_mobile\" "+ ":" + " \"7338954682\", "
			+" \"principal2_id_type\" "+ ":" + " \"PAN\", "
			+" \"principal2_passport\" "+ ":" + " \"ABBPB3212H\", "
			+" \"name_on_bank_account\" "+ ":" + " \"SILIGURI RC SUPPLY COMPANY\", "
			+" \"ifsc_code\" "+ ":" + " \"ICIC0000162\", "
			+" \"bank_name\" "+ ":" + " \"ICICI Bank Ltd\", "
			+" \"business_summary\" "+ ":" + " \"Furniture and Fittings\", "
			+" \"zero_day\" "+ ":" + " \"0\", "
			+" \"one_seven_day\" "+ ":" + " \"100\", "
			+" \"eight_fourteen_day\" "+ ":" + " \"0\", "
			+" \"fifteen_thirty_day\" "+ ":" + " \"0\", "
			+" \"over_thirty_day\" "+ ":" + " \"0\", "
			+" \"device_type\" "+ ":" + " \"\", "
			+" \"trans_notification_link\" "+ ":" + " \"https:///eazypaymbluat.icicibank.com/EazyPayApp/updateSwipeTxnStatus.do\", "
			+" \"tax_id\" "+ ":" + " \"\", "
			+" \"visaMasterMSF\" "+ ":" + " \"\", "
			+" \"amexMSF\" "+ ":" + " \"EZYAMX200\", "
			+" \"chargeslip\" " + ":"
					+"{"
							+" \"vas\" " + ":"
								+"["
									+ "{"
										+" \"vasName\" "+ ":" + " \"ChargeSlipType\","
										+" \"count\" "+ ":" + " \"1\","
										+" \"vasValue\" "+ ":" + " \"U\" "
									+ "},"
									+ "{"
										+" \"vasName\" "+ ":" + " \"ChargeSlipType\","
										+" \"count\" "+ ":" + " \"1\","
										+" \"vasValue\" "+ ":" + " \"U\" "
									+ "}"
								+"]"
						+"}"
			+ "}";

			

}
